In [22]:
import heapq
from typing import List

class CoolHeap:
    def __init__(self, mode, init_data=[]):
        self._data = []
        self.mode = mode
        
        for d in init_data:
            self.push(d)
            
    @property
    def data(self):
        if self.mode == "max":
            return [-i for i in self._data]
        else:
            return [i for i in self._data]

    def top(self):
        if self.mode == "max":
            return -self._data[0]
        else:
            return self._data[0]

    def push(self, val):
        if self.mode == "max":
            heapq.heappush(self._data, -val)
        else:
            heapq.heappush(self._data, val)

    def pop(self):
        if self.mode == "max":
            return -heapq.heappop(self._data)
        else:
            return heapq.heappop(self._data)
    
    def clear(self):
        self._data = []
        
    def empty(self):
        return len(self._data) == 0
    
    @property
    def size(self):
        return len(self._data)

In [30]:
q_max = CoolHeap("max",[])
q_min = CoolHeap("min", [])

In [31]:
values = [ 5, 2, 3, 1, 6, 4]

In [36]:
for idx, num in enumerate(values):
    
    if (q_max.empty() or q_max.top() > num):
        q_max.push(num)
    else:
        q_min.push(num)
    
    if q_max.size > q_min.size+1:
        q_min.push(q_max.pop())
    elif q_min.size > q_max.size+1:
        q_max.push(q_min.pop())
    
    if q_max.size == q_min.size:
        print("median {} ".format(values[:idx+1]), (q_max.top()+q_min.top())/2.)
    elif q_max.size > q_min.size:
        print("median {} ".format(values[:idx+1]), q_max.top())
    else:
        print("median {} ".format(values[:idx+1]), q_min.top())

median [5]  3
median [5, 2]  3.0
median [5, 2, 3]  3
median [5, 2, 3, 1]  3.0
median [5, 2, 3, 1, 6]  3
median [5, 2, 3, 1, 6, 4]  3.0

In [33]:
q_max.data

[2, 1]

In [34]:
q_min.data

[3, 5]

########
---
Num of Island problem

In [1]:
import numpy as np
import pandas as pd

def get_a_random_island(size):
    matrix = np.random.randint(0,2, size)
    return matrix

In [2]:
class Solution():
    def __init__(self, m): 
        self.m = m
        self.visited = np.zeros(shape=m.shape)
        display(pd.DataFrame(self.m))
    
    def run(self):
        count = 0
        for i in range(self.m.shape[0]):
            for j in range(self.m[0].shape[0]):
                if self.m[i,j]==1 and self.visited[i,j] == 0:
                    self.dfs(i,j)
                    count+=1
        return count
    
    def dfs(self,i,j):
        if (i<0 or i >= self.m.shape[0] or \
            j<0 or j>=self.m[0].shape[0] or \
            self.visited[i,j]==1 or \
            self.m[i,j]==0):
            return
        self.visited[i,j] = 1
        self.dfs(i,j+1)
        self.dfs(i,j-1)
        self.dfs(i+1,j)
        self.dfs(i-1,j)

In [3]:
%%time
M = get_a_random_island((10000,10000))
Solution(M).run()

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
0,1,1,1,0,1,0,1,0,1,1,...,0,0,1,0,1,1,1,0,0,1
1,1,0,0,0,0,0,1,1,0,0,...,1,0,1,1,0,0,1,1,1,0
2,0,1,1,1,1,1,1,1,0,1,...,0,1,1,0,1,1,0,0,1,1
3,1,1,1,1,1,0,0,1,0,1,...,0,1,1,1,1,0,1,1,1,1
4,1,0,0,1,1,0,1,0,0,0,...,0,1,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1,0,1,1,1,1,1,0,1,1,...,1,1,1,0,1,0,0,1,0,0
9996,0,1,1,1,0,1,1,0,1,1,...,1,0,0,0,1,0,0,0,1,1
9997,0,0,1,1,0,1,1,0,1,1,...,0,1,1,0,0,1,0,0,1,1
9998,1,0,1,1,1,0,1,0,1,0,...,0,1,0,0,0,0,1,0,0,1
9999,0,1,1,0,1,0,0,1,1,1,...,0,0,1,1,1,1,0,1,0,1

CPU times: user 8min 59s, sys: 5.46 s, total: 9min 4s
Wall time: 1h 31min 43s

6583137